name: Deploy to Somee

on:
  push:
    branches:
      - main  # Tự chạy khi bạn cập nhật nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to Somee via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp://traicay.somee.com
        username: huyen156
        password: ${{ secrets.SOMEE_FTP_PASSWORD }}
        server-dir: /wwwroot/
